In [4]:
import tensorflow as tf
import numpy as np
mat = tf.constant([[12, 23, 34, 45], [3, 25, 16, 1],
                 [78, 5, 23,27], [95,42,17,20]])
print(mat)
matmax = tf.math.reduce_max(mat,axis=1)
print(matmax)

tf.Tensor(
[[12 23 34 45]
 [ 3 25 16  1]
 [78  5 23 27]
 [95 42 17 20]], shape=(4, 4), dtype=int32)
tf.Tensor([45 25 78 95], shape=(4,), dtype=int32)


In [6]:
import tensorflow as tf
a=tf.constant([[1,2,3,4],[2,4,5,6],[1,1,1,1]])
b=tf.constant([[1,1,1,1],[7,2,2,3],[2,2,2,2]])
c=tf.add(a,b)
print(c)

tf.Tensor(
[[2 3 4 5]
 [9 6 7 9]
 [3 3 3 3]], shape=(3, 4), dtype=int32)


In [5]:
list = ([[1,3,2],[7,2,2],[2,2,2]])
a=tf.constant([[2,3,4],[1,3,4],[6,3,1]])
c=tf.add(list,a)
print(c)

tf.Tensor(
[[3 6 6]
 [8 5 6]
 [8 5 3]], shape=(3, 3), dtype=int32)
